# -*- coding: utf-8 -*-
"""books_recomendation_(1) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P9FknFa_wGAaZrjoj9j_vSOBmxcsOheJ
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from zipfile import ZipFile
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns

"""#**DATA UNDERSTANDING**"""

users = pd.read_csv("content/Users.csv")
ratings = pd.read_csv("content/Ratings.csv")
books = pd.read_csv("content/Books.csv", low_memory=False)

print('Jumlah User: ', len(users['User-ID'].unique()))
print('Jumlah Buku: ', len(books['ISBN'].unique()))
print('Jumlah Penilaian Buku: ', len(ratings['ISBN'].unique()))

"""#**DATA CLEANING**

### Ratings
"""

ratings.info()

ratings.describe(include='all')

ratings['Book-Rating'].value_counts()

"""**Interpretasi :**

- Berdasarkan hasil eksplorasi statistik terhadap kolom `Book-Rating`, ditemukan bahwa nilai **minimum hingga kuartil ke-2 (median) bernilai 0**, yang menunjukkan bahwa lebih dari 50% data rating tidak merepresentasikan preferensi pengguna.

- Distribusi ini menunjukkan adanya masalah sparsity dalam dataset, di mana sebagian besar interaksi user terhadap buku tidak menghasilkan penilaian yang bermakna.

- Untuk memperkuat analisis ini, dilakukan pengecekan lebih lanjut terhadap jumlah masing-masing nilai rating menggunakan `value_counts()`.

- Dari hasil tersebut ditemukan bahwa:
  - Sebanyak **716.109 rating (≈62%)** memiliki nilai 0.
  - Nilai rating dengan frekuensi tertinggi berikutnya adalah **rating 8 (103.736 rating)**, disusul oleh rating 10 dan 7.

Temuan ini menunjukkan bahwa data rating sangat **terdistribusi tidak merata**, dengan dominasi rating kosong yang signifikan. Oleh karena itu, data dengan nilai rating 0 akan dihapus dalam proses cleaning selanjutnya.

"""

ratings = ratings[ratings['Book-Rating'] != 0]
ratings['Book-Rating'].value_counts()

"""### Books"""

books.info()

"""**INSIGHT :**

- Berdasarkan hasil analisis sebelumnya, ditemukan bahwa banyak buku memiliki jumlah rating yang sangat sedikit. Untuk meningkatkan kualitas rekomendasi dan efisiensi komputasi, dipilih sebanyak 10.000 buku dengan jumlah rating terbanyak.

- Langkah ini didasarkan pada asumsi bahwa buku yang sering dinilai lebih relevan untuk direkomendasikan karena lebih banyak pengguna yang telah berinteraksi dengan buku tersebut.

"""

book_total = len(ratings['ISBN'].unique())
print("Jumlah Total ID Buku yang memiliki penilaian: ", book_total)

# Menghitung jumlah rating per buku
book_rating_counts = ratings['ISBN'].value_counts()

# Mengambil 10 ribu data buku terbanyak
top_books_isbn = book_rating_counts.head(10000).index
print(top_books_isbn)

# Mem-filter dataset rating dan book sesuai list isbn yg ada di top_book_isbn
ratings = ratings[ratings['ISBN'].isin(top_books_isbn)]
print("Jumlah Penilaian yang akan digunakan: ", len(ratings))

books = books[books['ISBN'].isin(top_books_isbn)]
print("Jumlah Buku: ", len(books))

"""**INTERPRETASI :**
- Dari 10.000 ISBN dengan jumlah rating terbanyak, hanya 9.548 yang berhasil digabungkan dengan data buku. Hal ini terjadi karena sebagian ISBN tidak memiliki informasi metadata yang lengkap, seperti judul atau penulis, sehingga tidak dapat digunakan dalam proses rekomendasi.
"""

users.info()

users = users[users['User-ID'].isin(ratings['User-ID'])]
print("JUmlah User: ", len(users))

"""**Interpretasi:**

Data pengguna dibersihkan dengan hanya mempertahankan user yang terdapat dalam data rating. Hal ini dilakukan karena pengguna di luar data rating tidak memiliki interaksi yang dapat dianalisis, sehingga tidak relevan untuk digunakan dalam proses rekomendasi.

#**EXPLORATORY DATA ANALYSIS**

## Distribusi Rating
"""

plt.figure(figsize=(10,6))
sns.countplot(data=ratings, x='Book-Rating', hue='Book-Rating', palette='viridis', legend=False)
plt.title('Distribusi Book Rating')
plt.xlabel('Rating')
plt.ylabel('Jumlah')
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""**Interpretasi :**

- Setelah menghapus rating dengan nilai 0, distribusi rating pengguna menunjukkan pola yang condong ke nilai tinggi. Rating 8, 10, dan 7 menjadi yang paling banyak diberikan oleh pengguna, mengindikasikan adanya kecenderungan pengguna untuk memberikan penilaian yang positif terhadap buku yang mereka baca.

- Pembersihan data rating ini membantu menghasilkan distribusi yang lebih merefleksikan preferensi aktual pengguna, karena nilai 0 sebelumnya diduga lebih menggambarkan ketidakterlibatan atau noise daripada opini yang valid.

## Top 10 Buku dengan Rating Terbanyak
"""

# Mengambil 10 ID buku dengan rating terbanyak
book_counts = ratings['ISBN'].value_counts().head(10)

# Mengambil Judul buku
top_books = book_counts.reset_index()
top_books.columns = ['ISBN', 'Book-Rating']
top_books = top_books.merge(books[['ISBN', 'Book-Title']], on='ISBN', how='left')

plt.figure(figsize=(10, 6))
sns.barplot(x=top_books['Book-Rating'], hue=top_books['Book-Rating'], y=top_books['Book-Title'], palette='crest', legend=False)
plt.xlabel('Jumlah Rating')
plt.ylabel('Judul Buku')
plt.title('Top 10 Buku dengan Jumlah Rating Terbanyak')
plt.show()

"""**Interpretasi :**
- Berdasarkan data rating yang telah dibersihkan (tanpa rating 0), buku dengan jumlah rating terbanyak adalah:

  - **The Lovely Bones** (~700 rating)
  - **Wild Animus** (~600 rating)
  - **The Da Vinci Code** (~500 rating)
  - **The Red Tent** (~400 rating)

- Meskipun merupakan buku paling populer dalam dataset, jumlah ratingnya masih relatif kecil. Ini menunjukkan bahwa secara umum dataset bersifat **sparse**, yaitu banyak buku yang hanya mendapatkan sedikit interaksi dari pengguna.

"""

# Hitung jumlah rating per user
user_counts = ratings['User-ID'].value_counts().head(10)

# Plot
plt.figure(figsize=(10, 6))
sns.barplot(x=user_counts.values, hue=user_counts.values, y=user_counts.index, palette='pastel')
plt.xlabel('Jumlah Rating')
plt.ylabel('User ID')
plt.title('Top 10 User dengan Rating Terbanyak')
plt.show()

"""#**DATA PREPROCESSING**

## Menggabungkan Data ratings dan book
"""

# contoh gabung ratings + books berdasarkan ISBN
ratings_books = pd.merge(ratings, books, on='ISBN', how='left')

print(ratings_books.info())

"""## Mengecek data ratings_book yang bernilai null"""

ratings_books.isnull().sum()

# menghapus yg null
ratings_books.dropna(inplace=True)
ratings_books.isnull().sum()

"""### Mengecek data ratings_book yang duplikat

"""

ratings_books.duplicated().sum()

"""### Menghapus beberapa fitur yang tidak diperlukan

"""

ratings_books = ratings_books.drop(columns=['Image-URL-S', 'Image-URL-M', 'Image-URL-L'])
ratings_books

fix_book = ratings_books.sort_values('ISBN', ascending=True)
fix_book

# Mengecek berapa jumlah buku yang ada di fix_book
len(fix_book.ISBN.unique())

# Membuat variabel preparation yang berisi dataframe fix_book kemudian mengurutkan berdasarkan ISBN
preparation = fix_book
preparation.sort_values('ISBN')

# Membuang data duplikat pada variabel preparation
preparation = preparation.drop_duplicates('ISBN')
preparation

# Mengonversi data series ‘ISBN’ menjadi dalam bentuk list
book_id = preparation['ISBN'].tolist()

# Mengonversi data series ‘Book-Title' menjadi dalam bentuk list
book_title = preparation['Book-Title'].tolist()

# Mengonversi data series ‘Book-Author’ menjadi dalam bentuk list
book_author = preparation['Book-Author'].tolist()

# Mengonversi data series ‘Publisher’ menjadi dalam bentuk list
book_publisher = preparation['Publisher'].tolist()

print(len(book_id))
print(len(book_author))
print(len(book_title))
print(len(book_publisher))

# Membuat dictionary untuk data ‘book_id’, ‘book_title’, dan ‘book_author’, dan 'book_publisher'
book_new = pd.DataFrame({
    'id': book_id,
    'title': book_title,
    'author': book_author,
    'publisher': book_publisher
})
book_new

book_new['combined_features'] = book_new['author'] + ' ' + book_new['publisher']

"""# MODEL DEVELOPMENT DENGAN CONTENT BASED FILTERING"""

data = book_new

"""## Inisialisasi TfidfVectorizer"""

tfidf = TfidfVectorizer()

tfidf.fit(data['combined_features'])
tfidf.get_feature_names_out()

# Melakukan fit lalu ditransformasikan ke bentuk matrix
tfidf_matrix = tfidf.fit_transform(data['combined_features'])

tfidf_matrix.shape

# Mengubah vektor tf-idf dalam bentuk matriks dengan fungsi todense()
tfidf_matrix.todense()

# Membuat dataframe untuk melihat tf-idf matrix

pd.DataFrame(
    tfidf_matrix.todense(),
    columns=tfidf.get_feature_names_out(),
    index=data.title
).sample(22, axis=1).sample(10, axis=0)

"""## Menghitung nilai Cosine Similarity"""

cosine_sim = cosine_similarity(tfidf_matrix)
cosine_sim

# Membuat dataframe dari variabel cosine_sim dengan baris dan kolom berupa Judul Buku
cosine_sim_df = pd.DataFrame(cosine_sim, index=data['title'], columns=data['title'])
print('Shape:', cosine_sim_df.shape)

# Melihat similarity matrix pada setiap buku
cosine_sim_df.sample(5, axis=1).sample(10, axis=0)

def book_recommendations(judul_buku, similarity_data=cosine_sim_df, items=data[['title', 'combined_features']], k=5):
    index = similarity_data.loc[:,judul_buku].to_numpy().argpartition(
        range(-1, -k, -1))

    closest = similarity_data.columns[index[-1:-(k+2):-1]]
    closest = closest.drop(judul_buku, errors='ignore')

    return pd.DataFrame(closest).merge(items).head(k)

data[data.title.eq('Shades Of Twilight')]

book_recommendations('Shades Of Twilight')

"""# MODEL DEVELOPMENT DENGAN COLLABORATIVE FILTERING"""

df = ratings
df

# ngeresample df baru berdasarkan data yg ada udah di resample di dataframe data
df['ISBN'] = df['ISBN'].astype(str)
data['id'] = data['id'].astype(str)

# Filter df hanya untuk ISBN yang ada di book_fix
df = df[df['ISBN'].isin(data['id'])]

# Menyimpan dataset rating yang fiks ke csv
df.to_csv('rating_final.csv', index=False)

"""## Encoding ID user"""

# Mengubah userID menjadi list tanpa nilai yang sama
user_ids = df['User-ID'].unique().tolist()
print('list User-ID: ', user_ids)

# Melakukan encoding userID
user_to_user_encoded = {x: i for i, x in enumerate(user_ids)}
print('encoded userID : ', user_to_user_encoded)

# Melakukan proses encoding angka ke ke userID
user_encoded_to_user = {i: x for i, x in enumerate(user_ids)}
print('encoded angka ke userID: ', user_encoded_to_user)

"""## Encoding ID book ( ISBN )"""

# Mengubah ISBN menjadi list tanpa nilai yang sama
book_ids = df['ISBN'].unique().tolist()

# Melakukan proses encoding placeID
book_to_book_encoded = {x: i for i, x in enumerate(book_ids)}

# Melakukan proses encoding angka ke placeID
book_encoded_to_book = {i: x for i, x in enumerate(book_ids)}

"""## Mapping user-id dan book-id ke dataframe df"""

df['user'] = df['User-ID'].map(user_to_user_encoded)
df['book'] = df['ISBN'].map(book_to_book_encoded)

df = df.copy()

# Mendapatkan jumlah user
num_users = len(user_to_user_encoded)
print(num_users)

# Mendapatkan jumlah resto
num_book = len(book_encoded_to_book)
print(num_book)

# Mengubah rating menjadi nilai float
df['Book-Rating'] = df['Book-Rating'].values.astype(np.float32)

# Nilai minimum rating
min_rating = min(df['Book-Rating'])

# Nilai maksimal rating
max_rating = max(df['Book-Rating'])

print('Number of User: {}, Number of Resto: {}, Min Rating: {}, Max Rating: {}'.format(
    num_users, num_book, min_rating, max_rating
))

"""## Shuffle dataset"""

df = df.sample(frac=1, random_state=42)
df

"""## Membagi Data untuk Training dan Validasi"""

x = df[['user', 'book']].values
y = df['Book-Rating'].apply(lambda x: (x - min_rating) / (max_rating - min_rating)).values

train_indices = int(0.8 * df.shape[0])
x_train, x_val, y_train, y_val = (
    x[:train_indices],
    x[train_indices:],
    y[:train_indices],
    y[train_indices:]
)

print(x, y)

"""## Membuat class RecommenderNet"""

class RecommenderNet(tf.keras.Model):
  def __init__(self, num_users, num_book, embedding_size, **kwargs):
    super(RecommenderNet, self).__init__(**kwargs)
    self.num_users = num_users
    self.num_resto = num_book
    self.embedding_size = embedding_size
    self.user_embedding = layers.Embedding(
        num_users,
        embedding_size,
        embeddings_initializer = 'he_normal',
        embeddings_regularizer = keras.regularizers.l2(1e-6)
    )
    self.user_bias = layers.Embedding(num_users, 1)
    self.book_embedding = layers.Embedding(
        num_book,
        embedding_size,
        embeddings_initializer = 'he_normal',
        embeddings_regularizer = keras.regularizers.l2(1e-6)
    )
    self.book_bias = layers.Embedding(num_book, 1)

  def call(self, inputs):
    user_vector = self.user_embedding(inputs[:,0])
    user_bias = self.user_bias(inputs[:, 0])
    book_vector = self.book_embedding(inputs[:, 1])
    book_bias = self.book_bias(inputs[:, 1])

    dot_user_book = tf.tensordot(user_vector, book_vector, 2)

    x = dot_user_book + user_bias + book_bias

    return x

"""## Inisialisasi Model"""

model = RecommenderNet(num_users, num_book, 50)

model.compile(
    loss='mse',
    optimizer='adam',
    metrics=['mae']
)

"""## Training Model"""

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)


history = model.fit(
    x = x_train,
    y = y_train,
    batch_size = 8,
    epochs = 50,
    validation_data = (x_val, y_val),
    callbacks=[early_stop]
)

"""## Membuat visualisasi Metrik"""

plt.plot(history.history['mae'], label='Training MAE')
plt.plot(history.history['val_mae'], label='Validation MAE')
plt.title('Model MAE per Epoch')
plt.xlabel('Epoch')
plt.ylabel('MAE')
plt.legend()
plt.grid(True)
plt.show()

"""## Insight :
1. Performa Meningkat di Awal
Pada beberapa epoch pertama, MAE menurun signifikan baik pada data training maupun validasi. Hal ini menunjukkan bahwa model cepat belajar pola dalam data.

2. Konsistensi Antara Training dan Validation
Sepanjang pelatihan, garis MAE training dan validation saling berdekatan, artinya model memiliki generalisasi yang baik (tidak hanya menghafal data training).

## Mendapatkan Rekomendasi Buku
"""

book_df = book_new
df = pd.read_csv('rating_final.csv')

# Mengambil sample user
user_id = df['User-ID'].sample(1).iloc[0]
book_has_read_by_user = df[df['User-ID'] == user_id]

book_has_not_read = book_df[~book_df['id'].isin(book_has_read_by_user.ISBN.values)]['id']
book_has_not_read = list(
    set(book_has_not_read)
    .intersection(set(book_to_book_encoded.keys()))
)

book_has_not_read = [[book_to_book_encoded.get(x)] for x in book_has_not_read]
user_encoder = user_to_user_encoded.get(user_id)
user_book_array = np.hstack(
    ([[user_encoder]] * len(book_has_not_read), book_has_not_read)
)

ratings = model.predict(user_book_array).flatten()

top_ratings_indices = ratings.argsort()[-10:][::-1]
recommended_book_ids = [
    book_encoded_to_book.get(book_has_not_read[x][0]) for x in top_ratings_indices
]

print('Showing recommendations for users: {}'.format(user_id))
print('===' * 9)
print('Book with high ratings from user')
print('----' * 8)

top_resto_user = (
    book_has_read_by_user.sort_values(
        by = 'Book-Rating',
        ascending=False
    )
    .head(5)
    .ISBN.values
)

book_df_rows = book_df[book_df['id'].isin(top_resto_user)]
for row in book_df_rows.itertuples():
    print(row.title, ':', row.author, ' dan ', row.publisher)

print('----' * 8)
print('Top 10 Books recommendation')
print('----' * 8)

recommended_book = book_df[book_df['id'].isin(recommended_book_ids)]
for row in recommended_book.itertuples():
    print(row.title, ':', row.author, ' dan ', row.publisher)